version: "3.3"
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend/Dockerfile_vue
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=${NODE_ENV}
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    networks:
      - api_bridge
  
  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend/Dockerfile_python
    volumes:
      - './backend:/usr/src/app'
      - '/usr/bin/git:/usr/bin/git'
      - './git-repo:/git-repo'
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env.development
    environment:
      - GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git
      - GIT_REPO_PATH=/git-repo
    depends_on:
      db:
        condition: service_healthy
    networks:
      - api_bridge
    restart: always
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './scripts/init.sql:/docker-entrypoint-initdb.d/init.sql'
    restart: always
    networks:
      - api_bridge
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --skip-character-set-client-handshake
      --bind-address=0.0.0.0
      --default-time-zone='+08:00'
      --init-file=/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - api_bridge
      
networks:
  api_bridge:
    driver: bridge
