FROM python:3.9-slim

WORKDIR /usr/src/app

# 安裝系統依賴
RUN apt-get update && apt-get install -y \
    git \
    && rm -rf /var/lib/apt/lists/*

# 確保配置目錄存在
RUN mkdir -p /usr/src/app/config

# 複製 requirements.txt
COPY ./backend/requirements.txt .

# 安裝依賴
RUN pip install --no-cache-dir -r requirements.txt

# 然後複製其餘的源代碼
COPY ./backend .

# 設置環境變量
ENV FLASK_APP=app.py
ENV PYTHONPATH=/usr/src/app
ENV FLASK_ENV=production
ENV GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/config/firebase-adminsdk.json

# 暴露端口
EXPOSE 5000

COPY ./backend/entrypoint.sh /usr/src/app/
RUN chmod +x /usr/src/app/entrypoint.sh

CMD ["/usr/src/app/entrypoint.sh"]